name: Hardware Test

on: [push]

jobs:
  test-board:
    runs-on: [self-hosted]
    env:
      ELF: "[/path/to/your/firmware.elf]"   # optional, runs code already on-board when left out
      ADDR: "[address to read]"
      TARGET: "[board architecture]"        # run `pyocd list --target` to see supported targets 
      BREAKPOINT: "[breakpoint address]"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install --upgrade pyocd
      - run: python flash_and_peek.py
