name: Example STM32F103RC Workflow

on: [push]

jobs:
  verify:
      uses: ./.github/workflows/verify.yml
      with:
        elf: './examples/STM32F103RC-blink.elf'
        addr: '0x40010c08'
        target: 'stm32f103rc'
        breakpoint: '0x08001f10'