name: Flash Firmware

on:
  workflow_call:
    inputs:
      firmware_path:
        required: true
        type: string
        description: "Path to the firmware file to flash"
      target:
        required: false
        type: string
        description: "Target board architecture (optional, defaults to auto-detected)"
        default: ''
    outputs:
      FLASHED:
        description: "Whether the device was successfully flashed"
        value: ${{ jobs.flash.outputs.FLASHED }}

jobs:
  flash:
    runs-on: self-hosted
    outputs:
      FLASHED: ${{ steps.set_output.outputs.FLASHED }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Flash device with pyOCD
        id: do_flash
        run: |
          if [ -n "${{ inputs.target }}" ]; then
            pyocd flash "${{ inputs.firmware_path }}" --target "${{ inputs.target }}"
          else
            pyocd flash "${{ inputs.firmware_path }}"
          fi

      - name: Set FLASHED output
        id: set_output
        if: steps.do_flash.conclusion == 'success'
        run: echo "FLASHED=true" >> $GITHUB_OUTPUT
