name: Flash Firmware

on:
  workflow_call:
    inputs:
      firmware_path:
        required: true
        type: string
        description: "Path to the firmware file to flash"
      target:
        required: false
        type: string
        description: "Target board architecture (optional, defaults to auto-detected)"
        default: ''
    outputs:
      FLASHED:
        description: "Whether the device was successfully flashed"
        value: ${{ jobs.flash.outputs.FLASHED }}

jobs:
  flash:
    runs-on: self-hosted
    outputs:
      FLASHED: ${{ steps.set_output.outputs.FLASHED }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Flash firmware (with --target)
        if: ${{ inputs.target != '' }}
        run: pyocd flash ${{ inputs.firmware_path }} --target ${{ inputs.target }}

      - name: Flash firmware (auto-detect)
        if: ${{ inputs.target == '' }}
        run: pyocd flash ${{ inputs.firmware_path }}


      - name: Set FLASHED output
        id: set_output
        if: success()
        run: echo "FLASHED=true" >> $GITHUB_OUTPUT
