name: Flash Firmware

on:
  workflow_call:
    inputs:
      firmware_path:
        required: true
        type: string
        description: "Path to the firmware file to flash"
      target:
        required: false
        type: string
        description: "Target board architecture (optional, defaults to auto-detected)"
        default: ''

jobs:
  flash:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Flash firmware (with --target)
        if: ${{ inputs.target != '' }}
        run: pyocd flash ${{ inputs.firmware_path }} --target ${{ inputs.target }}

      - name: Flash firmware (auto-detect)
        if: ${{ inputs.target == '' }}
        run: pyocd flash ${{ inputs.firmware_path }}
