name: Halt Target

on:
  workflow_call:
    inputs:
      breakpoint:
        required: false
        type: string
        description: "Breakpoint address or symbol to halt at"
        default: ''

jobs:

  halt:
    runs-on: self-hosted
    steps:
        - name: Reset target
          run: |
            pyocd cmd -c "reset halt"

        - name: Set breakpoint
          if: ${{ inputs.breakpoint != '' }}
          run: |
            pyocd cmd -c "break ${{ inputs.breakpoint }}"

        - name: Run target
          run: |
            pyocd cmd -c "continue"
