name: HIL-Test
on: [push]

jobs:
  hil:
    runs-on: ubuntu-latest          # hosted runner
    env:
      MAC_HOST:  100.68.193.6            # MagicDNS name or tail IP
      SSH_USER:  ${{ secrets.TEST_NAME }}
    steps:
      - uses: actions/checkout@v4

      # 1. Join the tailnet as an EPHEMERAL node (tagged ci-runner)
      - name: Connect to Tailnet
        uses: tailscale/github-action@v3
        with:
          authkey: ${{ secrets.TEST_TAILSCALE }}
        # (If you switched to OAuth: use oauth-client-id / oauth-secret instead)

      # 2. (Optional) Fail fast if the Mac can’t be reached
      - name: Ping the target
        run: tailscale ping -c 3 $MAC_HOST

      # 3. Run whatever you need on the Mac
      - name: Run HIL test
        run: |
          ssh -o StrictHostKeyChecking=no \
              -o IdentitiesOnly=yes \
              -o PreferredAuthentications=publickey \
              "$SSH_USER@$MAC_HOST" \
              echo "Hello from the Mac!"
