name: Example STM32F103RC Workflow

on: [push]

jobs:
  flash:
    uses: ./.github/workflows/flash-firmware.yml
    with:
      firmware_path: './examples/STM32F103RC-blink.elf'
      target: 'STM32F103RC'  # Specify the target architecture if needed

  halt:
    uses: ./.github/workflows/halt.yml
    needs: flash
    with:
      FLASHED: ${{ needs.flash.outputs.FLASHED }}
      breakpoint: 'main'  # Adjust this to the desired breakpoint address or symbol